import { z } from "zod/v4";

export const userSchema = z.object({
  // 'id' is auto-generated by the database (IDENTITY column)
  id: z.number().int().optional(),

  name: z
    .string()
    .min(2, { error: "Forneça um nome válido" })
    .max(50, { error: "Forneça um nome válido" }),

  // Email must be valid format
  email: z.email(),
});

export type UserType = z.infer<typeof userSchema>;
