import "@/app/styles/globals.css";
import { Manrope as ManropeFont } from "next/font/google";
import Header from "./_components/Header";

const manrope = ManropeFont({
  subsets: ["latin"],
  display: "swap",
});

export const metadata = {
  title: {
    template: "%s | Kaya",
    default: "Kaya",
  },
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${manrope.className} bg-stone-50 antialiased`}>
        <Header />
        {children}
      </body>
    </html>
  );
}
