import "@/app/styles/globals.css";
import { Quicksand } from "next/font/google";
import Header from "./_components/Header";
import { SessionProvider } from "next-auth/react";

const quicksand = Quicksand({
  subsets: ["latin"],
  display: "swap",
});

export const metadata = {
  title: {
    template: "%s | Kaya",
    default: "Kaya",
  },
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <SessionProvider>
        <body className={`${quicksand.className} antialiased`}>
          <Header />
          {children}
        </body>
      </SessionProvider>
    </html>
  );
}
